#!/usr/bin/env bash
# Adapted from redlib-org/redlib's updater; AGPL-3.0-only. See NOTICE.
set -euo pipefail

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
output="$root/crates/rdt-request/src/oauth_resources.rs"
if [[ ${1:-} == --output && $# == 2 ]]; then
  output="$2"
elif [[ $# != 0 ]]; then
  echo "Usage: $0 [--output FILE]" >&2
  exit 2
fi

fail() { echo "update_oauth_resources: $*" >&2; exit 1; }
fetch() {
  curl --fail --silent --show-error --location \
    --connect-timeout 10 --max-time 60 "$1"
}
for tool in curl rg sort mktemp; do
  command -v "$tool" >/dev/null || fail "Missing dependency: $tool"
done

# Write beside the destination so the final rename is atomic.
temporary="$(mktemp "$(dirname -- "$output")/.oauth_resources.XXXXXX")"
trap 'rm -f -- "$temporary"' EXIT

links=""
for page in 1 2 3 4 5; do
  url="https://apkcombo.com/reddit/com.reddit.frontpage/old-versions/"
  if [[ $page != 1 ]]; then
    url="https://apkcombo.com/reddit/com.reddit.frontpage/old-versions?page=$page"
  fi
  html="$(fetch "$url")" || fail "Could not fetch Android version page $page"
  page_links="$(printf '%s' "$html" | rg --only-matching \
    'href="(/reddit/com\.reddit\.frontpage/download/phone-20[0-9]{2}\.[0-9]+\.[0-9]+-apk)"' \
    --replace '$1')" || fail "No Android versions found on page $page"
  links+="$page_links"$'\n'
done

versions=()
while IFS= read -r path; do
  [[ -n $path ]] || continue
  html="$(fetch "https://apkcombo.com$path")" || fail "Could not fetch $path"
  version="$(printf '%s' "$html" | rg --only-matching \
    '<span class="vername">Reddit (20[0-9]{2}\.[0-9]+\.[0-9]+)</span>' \
    --replace '$1')" || fail "Missing version in $path"
  build="$(printf '%s' "$html" | rg --only-matching \
    '<span class="vercode">\(([0-9]+)\)</span>' \
    --replace '$1')" || fail "Missing build in $path"
  # Use the primary version/build, before variants and related releases (as upstream does).
  version="${version%%$'\n'*}"
  build="${build%%$'\n'*}"
  [[ $version =~ ^20[0-9]{2}\.[0-9]+\.[0-9]+$ && $build =~ ^[0-9]+$ ]] \
    || fail "Invalid or ambiguous version/build in $path"
  [[ $path == "/reddit/com.reddit.frontpage/download/phone-$version-apk" ]] \
    || fail "Version does not match download URL: $path"
  versions+=("Version $version/Build $build")
done < <(printf '%s' "$links" | sort -u)

[[ ${#versions[@]} -gt 0 ]] || fail "Empty Android version list"
{
  echo '// Generated by scripts/update_oauth_resources.sh; do not edit manually.'
  echo '// Android app versions from APKCombo. See NOTICE for upstream attribution.'
  printf 'pub const ANDROID_APP_VERSION_LIST: &[&str; %s] = &[\n' "${#versions[@]}"
  printf '    "%s",\n' "${versions[@]}"
  echo '];'
} > "$temporary"
chmod 644 "$temporary"
mv -f -- "$temporary" "$output"
echo "Updated $output (${#versions[@]} Android versions)"
