// Generated by scripts/update_oauth_resources.sh; do not edit manually.
// Android app versions from APKCombo. See NOTICE for upstream attribution.
pub const ANDROID_APP_VERSION_LIST: &[&str; 3] = &[
    "Version 2026.39.0/Build 2639040",
    "Version 2026.39.1/Build 2639070",
    "Version 2026.40.0/Build 2640011",
];
